### ISSUE TITLE
please add support for chrome on windows 10

### ISSUE THREAD

**Issue by alokbhaisahu** [pdf/kdeconnect-chrome-extension#51] opened 2022-09-27 15:49 UTC
i use kde connect for my mobile and tab daily and i find it very useful please add support for chrome on windows 10 .

**Comment by pdf** [comment] 2022-09-27 22:13
Duplicate of #39 

There is a PR with Windows support mostly complete, unfortunately it requires a rewrite of various other pieces of the code and I have not had the time to complete it. Work is ongoing.

**Closed as completed by pdf** 2022-09-27 22:13 UTC
Labels: duplicate
